version: "3.8"
services:
  database-bug-bash:
    image: postgres:16
    container_name: bug_bash_db
    environment:
      POSTGRES_DB: bug_bash
      POSTGRES_USER: bug_bash
      POSTGRES_PASSWORD: bug_bash
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - bug-bash-network

  ollama:
    container_name: ollama
    image: ollama/ollama
    ports:
      - "11434:11434"
    networks:
      - bug-bash-network
    volumes:
      - ollama_data:/root/.ollama
    entrypoint: ["/bin/sh", "-c", "ollama serve"]
    # (if it not works) docker exec -it ollama ollama pull codellama
    command:
      - "-c"
      - |
        ollama serve &
        until curl -s http://localhost:11434/api/tags > /dev/null; do sleep 2; done
        ollama pull codellama
        wait

  app:
    container_name: bug_bash_app
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    volumes:
      - ./src:/app/src
      - ./pom.xml:/app/pom.xml
    depends_on:
      - database-bug-bash
      - ollama
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - bug-bash-network
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database-bug-bash:5432/bug_bash
      OLLAMA_URL: http://ollama:11434
      OLLAMA_MODEL: codellama

networks:
  bug-bash-network:
    driver: bridge

volumes:
  postgres_data:
  ollama_data:
