version: "3.8"
services:
  database-bug-bash:
    image: postgres:16
    container_name: bug_bash_db
    environment:
      POSTGRES_DB: bug_bash
      POSTGRES_USER: bug_bash
      POSTGRES_PASSWORD: bug_bash
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - bug-bash-network

  ollama:
    container_name: ollama
    image: ollama/ollama
    networks:
      - bug-bash-network
    volumes:
      - ollama_data:/root/.ollama
    entrypoint: ["/bin/sh", "-c", "ollama serve"]
    command:
      - "-c"
      - |
        ollama serve & 
        sleep 10
        ollama pull codellama
        wait

  app:
    container_name: bug_bash_app_prod
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - database-bug-bash
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - bug-bash-network
    environment:
      # Overriding properties via environment variables
      SPRING_DATASOURCE_URL: jdbc:postgresql://database-bug-bash:5432/bug_bash
      OLLAMA_URL: http://ollama:11434
      OLLAMA_MODEL: codellama

networks:
  bug-bash-network:
    driver: bridge

volumes:
  postgres_data:
  ollama_data:
