server:
    port: 8080

app:
    base-url: ${APP_BASE_URL}
    frontend-url: ${APP_FRONTEND_URL}

auth:
    client-id: ${AUTH_CLIENT_ID}
    client-secret: ${AUTH_CLIENT_SECRET}
    redirect-uri-local: ${AUTH_REDIRECT_URI_LOCAL}
    redirect-uri-postman: ${AUTH_REDIRECT_URI_POSTMAN}

spring:
    config:
        import: optional:file:.env[.properties]

    application:
        name: bug-bash

    flyway:
        enabled: true
        baseline-on-migrate: true

    security:
        oauth2:
            client:
                registration:
                    github:
                        client-id: ${GITHUB_CLIENT_ID}
                        client-secret: ${GITHUB_CLIENT_SECRET}
                        redirect-uri: ${GITHUB_REDIRECT_URI:http://localhost:8080/login/oauth2/code/github}
                        scope:
                            - read:user
                            - user:email
                        
            resourceserver:
                jwt:
                    issuer-uri: ${app.base-url}

    datasource:
        password: ${DB_PASSWORD}
        username: ${DB_USERNAME}
        url: ${DB_URL}
        driver-class-name: org.postgresql.Driver

    sql:
        init:
            mode: never

ollama:
    model: "codellama" # This is the default value
    url: ${OLLAMA_URL}

logging:
    level:
        org.flywaydb: DEBUG
        org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver: ERROR
